window.COMPANY = {
  name: "コウキAIラボ",
  slogan: "3事業を、機能別AIチームで支える。",
  ceo: {
    name: "こうき",
    emoji: "🧑‍✈️",
    title: "代表取締役 CEO",
    note: "コールセンター7年＋インフラSE3年半。株式会社コホマダ（https://kohomadha.com/）のCOOを兼務し、海外進出支援事業を推進。あわせて株式会社DKN Enterprise（屋号KINOTO）の生活サービス事業、個人FP事業も展開する。",
  },
  secretary: {
    name: "アイ",
    emoji: "🤖",
    note: "AI秘書。全体の段取り役。こうき社長の右腕。",
  },
  employees: [
    { name: "ジン", emoji: "🛠️", role: "AI Chief of Staff／統括責任者", catch: "『やる』と決めたら、次の日には動いてます。",
      desc: "依頼の目的・対象事業を確認し、必要なエージェントだけを選定・委任し、成果物を統合する統括役。",
      skills: [], prompt: "ジン、この案件を整理して、必要なメンバーに振って" },
    { name: "リサ", emoji: "🔍", role: "Research & Evidence Analyst", catch: "事実、見つけてきます！",
      desc: "市場・競合・公式情報・制度の一次情報を調査する担当。事実と推測を分けて報告します。",
      skills: [], prompt: "リサ、この件について調べて" },
    { name: "レン", emoji: "🌏", role: "Business Development & Market Strategy Director", catch: "その国で勝てる筋、データで示します。",
      desc: "新規事業開発・海外展開/日本進出戦略・法人設立や販路開拓の実行計画までを担当。コホマダのマーケティング・市場調査領域を受け持つ。",
      skills: [], prompt: "レン、この事業戦略を考えて" },
    { name: "サトル", emoji: "🧭", role: "Growth Marketing & Revenue Strategist", catch: "数字で道筋を示します。",
      desc: "集客導線・営業導線・SNS/LINE戦略・KPI設計を担当。デザイン制作はカエデに委任します。",
      skills: [], prompt: "サトル、集客戦略を考えて" },
    { name: "カエデ", emoji: "🎨", role: "Creative & Brand Director", catch: "伝わる見せ方、形にします。",
      desc: "Canva/Wix/公式LINE/チラシ/営業資料のブランド・構成案を担当。技術実装はノヴァと連携します。",
      skills: [], prompt: "カエデ、このクリエイティブの構成案を考えて" },
    { name: "メイ", emoji: "🤖", role: "AI Automation & Operations Architect", catch: "その業務、つなげれば消えます。",
      desc: "業務分析・自動化候補の抽出・n8n設計統括を担当。実装はエイトに委任します。",
      skills: [], prompt: "メイ、この業務を自動化する仕組みを考えて" },
    { name: "エイト", emoji: "🔗", role: "n8n Workflow Implementation Engineer", catch: "その業務、n8nでつなぎます。",
      desc: "メイが設計した自動化要件のn8n実装を専門に担当（詳細は n8n-automation/ フォルダの専任エージェント体制と連携）。",
      skills: [], prompt: "エイト、この業務をn8nで自動化して" },
    { name: "ノヴァ", emoji: "🪐", role: "Web & Three.js Technical Architect", catch: "その表現、three.jsで動かしましょう。",
      desc: "3D企業サイト・インタラクティブ3D表現・Wix連携の技術実装/検証/最適化を担当。",
      skills: [], prompt: "ノヴァ、このサイトに3D演出を追加して",
      hair: "#3FBFAE", cloth: "#1F3A66", skin: "#C68A63", face: 5, hairStyle: 4, acc: "ac-headset" },
    { name: "ミナ", emoji: "💰", role: "Finance, FP & Subsidy Analyst", catch: "数字と制度、整理します。",
      desc: "事業収支・管理会計・FP計算・補助金/助成金調査を担当。個別金融商品の推奨や税務/法務の断定はしません。",
      skills: [], prompt: "ミナ、この収支を分析して",
      hair: "#6B5BA0", cloth: "#D98E8E", skin: "#F0C9A8", face: 6, hairStyle: 2, acc: "ac-clip" },
    { name: "リョウ", emoji: "⚖️", role: "Legal Research & Compliance Analyst", catch: "その契約、論点を整理しましょう。",
      desc: "契約書レビュー・法務リサーチ・許認可/コンプライアンス確認を担当。弁護士資格は持たないAI法務支援であり、正式な法律意見の代わりにはならない。重要案件・高リスク案件は必ず資格を有する弁護士の確認を挟む。",
      skills: [], prompt: "リョウ、この契約書をレビューして",
      hair: "#2A2E3A", cloth: "#3B4A66", skin: "#D9A57E", face: 2, hairStyle: 3, acc: "ac-glasses" },
    { name: "アオイ", emoji: "🔎", role: "Quality Assurance & Risk Auditor", catch: "最後は私がチェックします。",
      desc: "最終成果物を作成担当から独立してレビューする監査役。新規制作はせず、修正点と判定（PASS/PASS WITH CONDITIONS/REVISE/HUMAN REVIEW REQUIRED）を返す。",
      skills: [], prompt: "アオイ、この成果物を監査して",
      hair: "#4E6E58", cloth: "#7FB571", skin: "#EBC4A0", face: 9, hairStyle: 5, acc: "" },
  ],
};
