window.AI_STATE = {
  updatedAt: "2026-08-15T10:00:00+09:00",

  setup: {
    completed: true,
    steps: [
      { key: "design", label: "会社を設計する（あなたの情報を聞く）", done: true },
      { key: "launch", label: "会社を立ち上げる（設立・就任式）", done: true },
      { key: "office", label: "オフィスを開く（この画面）", done: true },
      { key: "gmail", label: "メール連携（任意）", done: true },
      { key: "calendar", label: "カレンダー連携（任意）", done: true },
      { key: "line", label: "LINE連携：外出先から指示（任意）", done: false },
      { key: "skills", label: "社員の専用ツールをつなぐ（任意・導入オプション）", done: false },
    ],
  },

  business: {
    goalLabel: "月間売上目標",
    goalAmount: 0,
    current: 0,
    pipeline: [
      { label: "応募", count: 0 },
      { label: "返信", count: 0 },
      { label: "受注", count: 0 },
    ],
  },

  tasks: [
    { id: "T1", title: "ガチャガチャ案件（コホマダ貿易）", owner: "レン", status: "todo", progress: 0, hint: "案件の現状整理から", cmd: "", log: [], deliverables: [] },
    { id: "T2", title: "トップパフォーマー案件（コホマダ貿易）", owner: "レン", status: "todo", progress: 0, hint: "案件の現状整理から", cmd: "", log: [], deliverables: [] },
    { id: "T3", title: "へウラ案件（コホマダ貿易）", owner: "レン", status: "todo", progress: 0, hint: "案件の現状整理から", cmd: "", log: [], deliverables: [] },
    { id: "T4", title: "貿易マッチングオンラインサロン構築（コホマダ貿易）", owner: "リサ", status: "todo", progress: 0, hint: "まずリサーチから着手", cmd: "", log: [], deliverables: [] },
    { id: "T5", title: "ノビオーシャン案件（コホマダ貿易）", owner: "レン", status: "todo", progress: 0, hint: "案件の現状整理から", cmd: "", log: [], deliverables: [] },
    { id: "T6", title: "「IF.」案件（コホマダ貿易）", owner: "レン", status: "todo", progress: 0, hint: "案件の現状整理から", cmd: "", log: [], deliverables: [] },
    { id: "T7", title: "アートサロン掛軸堂案件：中国モール出展支援（コホマダ貿易）", owner: "レン", status: "todo", progress: 0, hint: "出展プランの検討から", cmd: "", log: [], deliverables: [] },
    { id: "T8", title: "自社HP作成（コホマダ）", owner: "カエデ", status: "todo", progress: 0, hint: "構成案の作成から", cmd: "", log: [], deliverables: [] },
    { id: "T9", title: "ブックオフコーポレーション案件（コホマダAI）", owner: "メイ", status: "todo", progress: 0, hint: "案件の現状整理から", cmd: "", log: [], deliverables: [] },
    { id: "T10", title: "美容師業界向け「自動化」サービス構築（コホマダAI）", owner: "メイ", status: "todo", progress: 0, hint: "サービス要件の整理から", cmd: "", log: [], deliverables: [] },
    { id: "T11", title: "リスペクトマリン案件：ディスカバリーコール準備の最終化", owner: "レン", status: "done", progress: 100, hint: "社長承認済み。あとは社長／営業担当によるディスカバリーコール実施を待つのみ", cmd: "", log: [ { time: "now", text: "Google Drive上に下書き2件（コール準備資料）・見積分析レポート済み。正式法人名（Respect Surveyors/Respect Marine混在）ほか未確認事項多数あり" }, { time: "now", text: "下書き2件が完全重複と判明。ブリーフの先方回答（ポルトガル語）を確認し、T21・T22を反映したコールアジェンダを作成" }, { time: "now", text: "社長が資料確認・承認" } ], deliverables: [ { title: "T11 コール準備統合版", type: "md", at: "now", path: "logs/kohomada_2026-07-28_T11コール準備統合_v1.md" } ] },
    { id: "T12", title: "ファンドコミュニティ構築（コホマダ金融）", owner: "ミナ", status: "todo", progress: 0, hint: "コミュニティ設計の検討から", cmd: "", log: [], deliverables: [] },
    { id: "T13", title: "会計ツールのコンバータ構築（コホマダ金融）", owner: "ミナ", status: "todo", progress: 0, hint: "要件整理から", cmd: "", log: [], deliverables: [] },
    { id: "T14", title: "掛軸堂様：クラウドファンディング支援（KINOTO）", owner: "レン", status: "todo", progress: 0, hint: "支援内容の整理から", cmd: "", log: [], deliverables: [] },
    { id: "T15", title: "KINOTO用「事業計画書」作成", owner: "レン", status: "todo", progress: 0, hint: "骨子作成から", cmd: "", log: [], deliverables: [] },
    { id: "T16", title: "KINOTO HP作成", owner: "カエデ", status: "todo", progress: 0, hint: "構成案の作成から", cmd: "", log: [], deliverables: [] },
    { id: "T17", title: "KINOTO Instagram運用", owner: "サトル", status: "todo", progress: 0, hint: "運用方針の整理から", cmd: "", log: [], deliverables: [] },
    { id: "T18", title: "KINOTO Googleビジネスプロフィール構築", owner: "サトル", status: "todo", progress: 0, hint: "登録情報の整理から", cmd: "", log: [], deliverables: [] },
    { id: "T19", title: "KINOTO メタ広告（Instagram）用画像作成", owner: "カエデ", status: "todo", progress: 0, hint: "素材方針の検討から", cmd: "", log: [], deliverables: [] },
    { id: "T20", title: "KINOTO 公式LINE運用", owner: "カエデ", status: "todo", progress: 0, hint: "運用設計から", cmd: "", log: [], deliverables: [] },
    { id: "T21", title: "リスペクトマリン案件：未確認事項の追加リサーチ", owner: "リサ", status: "done", progress: 100, hint: "社長承認済み。正式法人名はディスカバリーコールで最終確認予定", cmd: "", log: [ { time: "now", text: "調査に着手" }, { time: "now", text: "CNPJ登記・業界他社・LGPD概要を調査完了。正式法人名は民間データベースの二次情報にとどまり未確定" }, { time: "now", text: "社長が資料確認・承認" } ], deliverables: [ { title: "T21 未確認事項リサーチ", type: "md", at: "now", path: "logs/kohomada_2026-07-27_T21要確認事項リサーチ_v1.md" } ] },
    { id: "T22", title: "リスペクトマリン案件：契約・LGPD論点整理", owner: "リョウ", status: "done", progress: 100, hint: "社長承認済み。契約書起案時・ブラジル現地弁護士相談時にこの整理を土台として使う", cmd: "", log: [ { time: "now", text: "論点整理に着手" }, { time: "now", text: "LGPD・段階契約・クロスボーダー論点整理が完了。正式法人名未確定・現地弁護士確認必須の旨を明記" }, { time: "now", text: "社長が資料確認・承認" } ], deliverables: [ { title: "T22 契約・LGPD論点整理", type: "md", at: "now", path: "logs/kohomada_2026-07-27_T22契約LGPD論点整理_v1.md" } ] },
    { id: "T23", title: "リスペクトマリン案件：コール準備資料・見積りの品質監査", owner: "アオイ", status: "done", progress: 100, hint: "判定：PASS WITH CONDITIONS。指摘6件の反映を社長が確認済み", cmd: "", log: [ { time: "now", text: "監査に着手（Q11の正確な趣旨は社長確認待ちのため、その点は判定対象から除外）" }, { time: "now", text: "PASS WITH CONDITIONSで完了。指摘6件をT11・T21・T22・T24へ反映済み" }, { time: "now", text: "社長が指摘反映を確認" } ], deliverables: [ { title: "T23 品質監査レポート", type: "md", at: "now", path: "logs/kohomada_2026-07-28_T23品質監査_v1.md" } ] },
    { id: "T24", title: "リスペクトマリン案件：Q11事前確認メールの下書き", owner: "レン", status: "review", progress: 100, hint: "文面は社長承認済み。ただし送信先メールアドレス・宛名（担当者名）が未確定のため、Gmail下書き化・送信はまだできない。社長に確認中", cmd: "", log: [ { time: "now", text: "T11のフォローとして下書き作成。未送信" }, { time: "now", text: "社長が文面を承認。送信先情報の確認待ち" } ], deliverables: [ { title: "T24 Q11確認メール下書き", type: "md", at: "now", path: "logs/kohomada_2026-07-28_T24Q11確認メール下書き_v1.md" } ] },
    { id: "T25", title: "リスペクトマリン案件：自動化アーキテクチャ設計（フェーズ別）", owner: "メイ", status: "review", progress: 100, hint: "社長承認済み（暫定版として）。ディスカバリーコールで通信環境・データ量等が判明次第、確定版（v2）を作成予定", cmd: "", log: [ { time: "now", text: "設計に着手（T21未確認事項・T22 LGPD論点を前提条件として反映）" }, { time: "now", text: "Phase1自動化設計が完成。業務フロー・n8n委任範囲・承認ポイント・LGPD反映まで整理" }, { time: "now", text: "社長が承認。ディスカバリーコール後に確定版を作成する方針を確認" } ], deliverables: [ { title: "T25 自動化アーキテクチャ設計", type: "md", at: "now", path: "logs/kohomada_2026-07-28_T25自動化アーキテクチャ設計_v1.md" } ] },
    { id: "T26", title: "リスペクトマリン案件：WhatsApp連携・ストレージ仕様・ANPD期限の一次情報確認", owner: "リサ", status: "done", progress: 100, hint: "社長確認済み", cmd: "", log: [ { time: "now", text: "調査に着手" }, { time: "now", text: "3点とも一次/準一次情報で裏付け完了。ANPD公布日に1件だけ齟齬(23日/26日)があり要原文確認" }, { time: "now", text: "社長が確認" } ], deliverables: [ { title: "T26 WhatsApp/Supabase/ANPD確認", type: "md", at: "now", path: "logs/kohomada_2026-07-28_T26WhatsApp_Supabase_ANPD確認_v1.md" } ] },
    { id: "T27", title: "リスペクトマリン案件：n8nワークフロー設計書（通知・承認フロー）", owner: "エイト", status: "review", progress: 100, hint: "社長確認済み。WhatsAppの下書き制約についてはメイ・社長の判断が必要と社長も認識（T31でメイに意見を求め中）", cmd: "", log: [ { time: "now", text: "設計に着手" }, { time: "now", text: "設計完了。WhatsAppノードの下書き機能欠如という新たなリスクを発見" }, { time: "now", text: "社長が確認。WhatsAppの扱いは要判断のまま" } ], deliverables: [ { title: "T27 n8nワークフロー設計書", type: "md", at: "now", path: "logs/kohomada_2026-07-28_T27n8nワークフロー設計書_v1.md" } ] },
    { id: "T28", title: "リスペクトマリン案件：デモ用n8nワークフローJSON実装（①④⑤メール版）", owner: "エイト", status: "done", progress: 100, hint: "社長確認済み。実インスタンスでの検証は社長がn8n環境を用意次第", cmd: "", log: [ { time: "now", text: "実装に着手（デモ用・本番未接続）" }, { time: "now", text: "①④⑤のワークフローJSON実装完了。未検証・未接続" }, { time: "now", text: "社長が確認" } ], deliverables: [ { title: "T28 n8nデモワークフローJSON", type: "md", at: "now", path: "logs/kohomada_2026-07-28_T28n8nデモワークフローJSON_v1.md" } ] },
    { id: "T29", title: "リスペクトマリン案件：社内共有用サマリー作成＋n8nワークフローのファイル整理", owner: "ジン", status: "done", progress: 100, hint: "案件サマリーを作成し、n8nワークフロー3件を単体JSONファイル化してn8n-workflows/フォルダに整理（README付き）。社内共有の準備完了", cmd: "", log: [ { time: "now", text: "サマリー作成、JSON分離、README作成すべて完了" } ], deliverables: [ { title: "案件サマリー", type: "md", at: "now", path: "logs/kohomada_2026-07-28_案件サマリー_v1.md" }, { title: "n8nワークフロー一式(JSON×3+README)", type: "folder", at: "now", path: "n8n-workflows/" } ] },
    { id: "T30", title: "リスペクトマリン案件：Googleドキュメント化＋ワークフロー設計図の作成", owner: "ジン", status: "done", progress: 100, hint: "案件サマリーをGoogleドキュメント化し、3ワークフローの初心者向け設計図（SVG×3＋まとめページ）を作成。社内共有の準備完了", cmd: "", log: [ { time: "now", text: "Googleドキュメント作成・設計図作成・Artifact公開すべて完了" } ], deliverables: [ { title: "Googleドキュメント（案件サマリー）", type: "gdoc", at: "now", path: "https://docs.google.com/document/d/19iCIyLTTeYxj9hnsWzq1IDkMyrcX3pa0O6Vl465LJcs/edit" }, { title: "ワークフロー設計図（3件・初心者向け）", type: "artifact", at: "now", path: "https://claude.ai/code/artifact/4b53078f-86ca-481a-94e7-2ce1bb14c5f8" }, { title: "設計図SVGファイル一式", type: "folder", at: "now", path: "n8n-workflows/diagrams/" } ] },
    { id: "T31", title: "KINOTO 総合チラシ制作（店頭・接点設置用）", owner: "カエデ", status: "review", progress: 90, hint: "success-case-research（他社事例調査）を反映した第3版4案（v3）をCanvaに登録・フォルダ格納済み。v1(4案)・v2(4案)と合わせて計12案。おすすめはv3", cmd: "T31はv3の1番の案で進めて", log: [ { time: "now", text: "サトルが訴求軸を整理：地域密着の「暮らしの何でも相談窓口」ポジショニング、ターゲットは中高年〜高齢者とご家族、遺品整理・生前整理を含むため落ち着いたトーンを指定" }, { time: "now", text: "カエデがCanva MCP（generate-design）で無料プラン前提の4案（v1）を生成" }, { time: "now", text: "候補プレビューのリンクが社長の画面で開けなかったため、4案とも社長のCanvaアカウントに正式登録（create-design-from-candidate）し直した" }, { time: "now", text: "社長の指示で「Claude作成デザイン」フォルダ（folder_id: FAHQpxqqkYc）を新設し、4案すべてを格納。以後Claude経由の制作物は必ずこのフォルダに保存する運用に" }, { time: "now", text: "T32で追加したSTP/C.R.A.P./AIDA等のフレームワークを反映し、改訂版4案（v2）を再生成" }, { time: "now", text: "リサがWebSearchで不用品回収・遺品整理・便利屋業のチラシ集客に関する業界メディア記事を調査（特定企業名の一次情報の成功事例は見つからず、複数の業界メディア・ポスティング事業者記事による二次情報として、季節配布タイミング・反復配布・明確なCTA・高齢層向けの大きな文字とシンプルなレイアウト・配色3色以内、という傾向を確認）" }, { time: "now", text: "サトルがこれらの傾向をSTPフレームワークで自社(KINOTO)に翻訳。カエデがキャッチコピー拡大・文字サイズ拡大・配色3色以内を反映した第3版4案（v3）を生成し、最初から正式登録・フォルダ格納まで実施" } ], deliverables: [ { title: "v1-案1：Calm Flyer Design for KINOTO Services", type: "canva", at: "now", url: "https://www.canva.com/d/dsFw-cWoyJBy6Si" }, { title: "v1-案2：Trustworthy Brochure for KINOTO Services", type: "canva", at: "now", url: "https://www.canva.com/d/76yu87NP3eqbfNY" }, { title: "v1-案3：チラシ - 暮らしの相談窓口", type: "canva", at: "now", url: "https://www.canva.com/d/lh_AYGeyy0I5LIz" }, { title: "v1-案4：チラシ - 暮らしのお困りごと まとめてご相談ください", type: "canva", at: "now", url: "https://www.canva.com/d/I_or0zD5a0zBtHo" }, { title: "v2-案1：チラシ - 生活サービスのご相談", type: "canva", at: "now", url: "https://www.canva.com/d/Y0MO7aNZqWUuKpv" }, { title: "v2-案2：KINOTO Integrated Lifestyle Services Flyer - Warm Design", type: "canva", at: "now", url: "https://www.canva.com/d/7KupI12meoZA3hj" }, { title: "v2-案3：KINOTO Lifestyle Services Flyer - Modern Design", type: "canva", at: "now", url: "https://www.canva.com/d/hui0qLo_lUAUvFt" }, { title: "v2-案4：Community Multipurpose Service Flyer - Structured Layout", type: "canva", at: "now", url: "https://www.canva.com/d/oEhP9_ErHRf4ZMO" }, { title: "v3-案1：チラシ - 暮らしのお困りごと", type: "canva", at: "now", url: "https://www.canva.com/d/opY0IBlNJCWB-K9" }, { title: "v3-案2：Spacious Flyer with Readable Elements", type: "canva", at: "now", url: "https://www.canva.com/d/5LG7e6dbZAex8Vj" }, { title: "v3-案3：Warm Navy Flyer for KINOTO Services", type: "canva", at: "now", url: "https://www.canva.com/d/zoVduGOHQmITjH1" }, { title: "v3-案4：Tri-Color Flyer for Life Services", type: "canva", at: "now", url: "https://www.canva.com/d/PAM0D7nHEG5mErm" } ] },
    { id: "T32", title: "クリエイティブ制作の基礎スキル強化（リサーチ／マーケ／デザイン／コピー）", owner: "ジン", status: "done", progress: 100, hint: "リサ・サトル・カエデ担当分、標準フレームワークをSkill/エージェント定義に追加完了。今後の制作物の質に反映される想定", cmd: "", log: [ { time: "now", text: "リサ：market-research-protocolに3C・SWOT・PEST・5フォース・ペルソナ設計の観点を追加" }, { time: "now", text: "サトル：自身のエージェント定義にSTP・4P/4C・ファネル設計・KPI階層・カスタマージャーニーを追加" }, { time: "now", text: "カエデ：canva-creative-productionにC.R.A.P.原則・配色比率・タイポグラフィ・余白等のデザイン原則を追加" }, { time: "now", text: "カエデ・サトル：copywritingにAIDA・PAS・PREP・FAB・見出し作成の観点を追加" } ], deliverables: [ { title: "market-research-protocol/protocol.md（更新）", type: "skill", at: "now", path: "AICompany/.claude/skills/market-research-protocol/protocol.md" }, { title: "copywriting/reference.md（更新）", type: "skill", at: "now", path: "AICompany/.claude/skills/copywriting/reference.md" }, { title: "satoru-growth-strategist.md（更新）", type: "agent", at: "now", path: "AICompany/.claude/agents/satoru-growth-strategist.md" }, { title: "canva-creative-production/SKILL.md（更新）", type: "skill", at: "now", path: "AICompany/.claude/skills/canva-creative-production/SKILL.md" } ] },
    { id: "T33", title: "他社成功事例リサーチ→分析→クリエイティブ反映フローの構築", owner: "ジン", status: "done", progress: 100, hint: "success-case-researchを新設し、canva-creative-production/sns-operation/official-line-design/sales-proposal-productionの標準フローに標準ステップとして組み込み済み（任意手順ではない）。以後クリエイティブ制作依頼で自動的に通る", cmd: "", log: [ { time: "now", text: "新Skill「success-case-research」を作成。事例の記録項目・見つからない場合の定型文・成功要因分析・自社翻訳・クリエイティブ反映・アオイ監査までの7ステップを定義" }, { time: "now", text: "リサ・サトル・カエデの各エージェント定義に参照Skillとして追加。CLAUDE.mdのSkill一覧にも登録" }, { time: "now", text: "社長より「クリエイティブ構築のフローに組み込む意図だった」と明確化。canva-creative-production（目的確認直後の標準ステップ2）・sns-operation・official-line-design・sales-proposal-productionに、任意ではなくデフォルト工程として埋め込み直した" } ], deliverables: [ { title: "success-case-research/SKILL.md（新規）", type: "skill", at: "now", path: "AICompany/.claude/skills/success-case-research/SKILL.md" } ] },
    { id: "T34", title: "note収益化：制度・手数料・特商法要件の調査（コホマダ）", owner: "リサ", status: "done", progress: 100, hint: "制度面の未確認事項はすべて確定。定期購読マガジンは運営中の価格変更が不可（変更には新マガジン作成＋旧マガジン終了が必要）と確定", cmd: "T34を確認しました", log: [ { time: "now", text: "note収益化の3形態と特商法表記ページを確認。手数料率は当初二次情報のみ" }, { time: "now", text: "社長共有の一次情報で価格帯・定期購読の発行条件を確定" }, { time: "now", text: "定期購読マガジンは運営中の価格変更不可と確定。これで制度面の未確認事項は解消" } ], deliverables: [ { title: "note収益化制度調査", type: "md", at: "now", path: "logs/kohomada_2026-07-28_note収益化制度調査_v1.md" } ] },
    { id: "T35", title: "note収益化：導線・価格戦略のたたき台（コホマダ）", owner: "サトル", status: "review", progress: 100, hint: "両論併記（社長指示）で有料記事単発／定期購読マガジンを比較。叩き台として「定期購読を軸＋反響記事は単発切り出し」の併用案を提示。価格帯はT34の手数料率確定待ちの暫定値", cmd: "T35を確認しました。この方向で進めて", log: [ { time: "now", text: "社長より「両論併記」の指示。有料記事単発・定期購読マガジンの2モデルをファネル/KPI/メリデメで比較し、併用型の叩き台と暫定価格帯を提示" } ], deliverables: [ { title: "note収益化導線_有料記事vs定期購読", type: "md", at: "now", path: "logs/kohomada_2026-07-28_note収益化導線_有料記事vs定期購読_v1.md" } ] },
    { id: "T36", title: "note収益化：特定商取引法表示・規約論点整理（コホマダ）", owner: "リョウ", status: "review", progress: 100, hint: "コホマダは法人運用のため「業として」の該当性は高いとの推測を整理。表示義務・リスク・弁護士確認事項を整理済み。条文原文の一次確認（e-Gov）は次のアクションとして残す", cmd: "T36を確認しました。弁護士確認の要否は追って判断します", log: [ { time: "now", text: "note運営の特商法表記ページを踏まえ、コホマダ（法人運用）の該当性・表示義務・リスクを整理。条文原文の一次確認は未実施として明記" } ], deliverables: [ { title: "note収益化_特商法論点整理", type: "md", at: "now", path: "logs/kohomada_2026-07-28_note収益化_特商法論点整理_v1.md" } ] },
    { id: "T37", title: "note収益化：価格設定・手取り試算（コホマダ）", owner: "ミナ", status: "done", progress: 100, hint: "確定手数料・確定制度で試算完了。定期購読は運営中の価格変更が不可（変更＝新マガジン作成＋旧終了）と判明したため、単発記事で反応を見てから定期購読価格を決める順番を提案。定期購読は保守的な価格からの開始を推奨", cmd: "T37を確認しました。この順番で進めます", log: [ { time: "now", text: "社長共有のnote公式ヘルプ本文で試算。「10%＋30円」という旧・二次情報は不正確だったと判明・訂正" }, { time: "now", text: "追加共有を反映し、noteプレミアム月会費500円を固定費として損益分岐試算に追加" }, { time: "now", text: "定期購読の価格変更不可が確定したため、単発記事での価格検証→定期購読価格決定という進め方を提案。これで全ての想定質問が解消" } ], deliverables: [ { title: "note収益化_価格設定手取り試算", type: "md", at: "now", path: "logs/kohomada_2026-07-28_note収益化_価格設定手取り試算_v1.md" } ] },
    { id: "T38", title: "note収益化：売れる有料コンテンツの傾向リサーチ（コホマダ）", owner: "リサ", status: "review", progress: 100, hint: "社長の「どんなコンテンツならお金に変わるか」を受けて調査。定期購読マガジンの発行要件（プレミアム会員登録・事前審査・価格変更不可）等の追加情報も含むが、いずれも二次情報にとどまり要一次確認", cmd: "T38を確認しました", log: [ { time: "now", text: "売れる有料記事の型（結論→理由→実例→まとめ、テンプレ/実績/DL素材が鍵）と定期購読マガジンの制度詳細を調査。貿易特化の売れ筋事例は見つからず" } ], deliverables: [ { title: "note収益化_売れるコンテンツリサーチ", type: "md", at: "now", path: "logs/kohomada_2026-07-28_note収益化_売れるコンテンツリサーチ_v1.md" } ] },
    { id: "T39", title: "note収益化：キャッシュに繋がるコンテンツ戦略（コホマダ）", owner: "サトル", status: "review", progress: 100, hint: "T38を踏まえ、貿易/AI・DX/金融の3領域ごとに有料化候補（テンプレ・チェックリスト・DL素材）を具体化。無料＝信頼構築、有料＝実行支援の切り分けを提案。実績数値の扱いに要注意点あり", cmd: "T39を確認しました。この候補で1本目を検討します", log: [ { time: "now", text: "リサの調査（T38）を踏まえ、コホマダ3領域ごとの有料コンテンツ候補と無料/有料の切り分けを整理。カエデへの制作依頼粒度も先出しで整理" } ], deliverables: [ { title: "note収益化_コンテンツ戦略", type: "md", at: "now", path: "logs/kohomada_2026-07-28_note収益化_コンテンツ戦略_v1.md" } ] },
    { id: "T40", title: "有料コンテンツ制作：国別輸出入規制 確認フレームワーク（コホマダ貿易）", owner: "レン", status: "review", progress: 100, hint: "実案件データなしのため、特定国の税率・規制を断定せず「何を確認すべきか」の8項目フレームワークとして作成。鈴木さんの実務上の『よくある見落とし』一言があれば差別化になる", cmd: "T40を確認しました", log: [ { time: "now", text: "社長の承認内容（実案件情報なし）を踏まえ、国・品目を問わず使える確認項目フレームワークとして作成" } ], deliverables: [ { title: "有料コンテンツ_国別輸出入規制確認フレームワーク", type: "md", at: "now", path: "logs/kohomada_2026-07-28_有料コンテンツ_国別輸出入規制確認フレームワーク_v1.md" } ] },
    { id: "T41", title: "有料コンテンツ制作：海外バイヤー開拓メールテンプレ集（コホマダ貿易）", owner: "サトル", status: "review", progress: 100, hint: "初回接触〜クロージングまで4段階、AIDA/PAS/PREPで構成した英文テンプレ＋解説を作成", cmd: "T41を確認しました", log: [ { time: "now", text: "copywritingスキルの型を使い、段階別テンプレを作成" } ], deliverables: [ { title: "有料コンテンツ_海外バイヤー開拓メールテンプレ集", type: "md", at: "now", path: "logs/kohomada_2026-07-28_有料コンテンツ_海外バイヤー開拓メールテンプレ集_v1.md" } ] },
    { id: "T42", title: "有料コンテンツ制作：貿易実務書類ひな形（コホマダ貿易）", owner: "レン", status: "review", progress: 100, hint: "インボイス・パッキングリスト・原産地証明書・船積依頼書の一般的な記載項目を整理。正式様式の断定は避け、専門家確認前提を明記", cmd: "T42を確認しました", log: [ { time: "now", text: "国際貿易実務で一般的な記載項目の型として作成" } ], deliverables: [ { title: "有料コンテンツ_貿易実務書類ひな形", type: "md", at: "now", path: "logs/kohomada_2026-07-28_有料コンテンツ_貿易実務書類ひな形_v1.md" } ] },
    { id: "T43", title: "有料コンテンツ制作：業種別AI導入ROI試算シート（コホマダAI）", owner: "ミナ", status: "review", progress: 100, hint: "業界平均値は断定せず、読者が自社数値を入力して使う計算構造（削減時間×単価→純便益→回収期間→ROI%）として設計。次はスプレッドシート実装", cmd: "T43を確認しました", log: [ { time: "now", text: "試算シートの構成（入力欄・自動計算欄・業種別入力例）を設計" } ], deliverables: [ { title: "有料コンテンツ_AI導入ROI試算シート", type: "md", at: "now", path: "logs/kohomada_2026-07-28_有料コンテンツ_AI導入ROI試算シート_v1.md" } ] },
    { id: "T44", title: "有料コンテンツ制作：AI・DX導入プロセスチェックリスト（コホマダAI）", owner: "メイ", status: "review", progress: 100, hint: "要件定義→ベンダー選定→導入→運用の4フェーズでチェックリスト化。特定ベンダー名は挙げず汎用的な観点整理", cmd: "T44を確認しました", log: [ { time: "now", text: "4フェーズのチェックリストを作成" } ], deliverables: [ { title: "有料コンテンツ_AI導入プロセスチェックリスト", type: "md", at: "now", path: "logs/kohomada_2026-07-28_有料コンテンツ_AI導入プロセスチェックリスト_v1.md" } ] },
    { id: "T45", title: "有料コンテンツ制作：n8nワークフロー汎用テンプレ集（コホマダAI）", owner: "エイト", status: "review", progress: 60, hint: "既存3ワークフロー（T27/T28・船舶検査業向けデモ）を業種を問わない汎用フィールド名に置き換える企画のみ完成。実際の汎用JSONファイル作成・動作検証はこの方向性の承認後に着手", cmd: "T45を確認しました。この方向でJSON化を進めて", log: [ { time: "now", text: "既存ワークフローの汎用化パターン（承認依頼/新規登録通知/下書き作成通知）を企画。実JSON未作成であることを明記" } ], deliverables: [ { title: "有料コンテンツ_n8nワークフロー汎用テンプレ集（企画）", type: "md", at: "now", path: "logs/kohomada_2026-07-28_有料コンテンツ_n8nワークフロー汎用テンプレ集_v1.md" } ] },
    { id: "T46", title: "有料コンテンツ制作：資金調達・補助金活用の実務チェックリスト（コホマダ金融）", owner: "ミナ", status: "review", progress: 100, hint: "特定の補助金制度名・金額は挙げず、公募要領の読み方〜実行フェーズまでの汎用チェックリストとして作成", cmd: "T46を確認しました", log: [ { time: "now", text: "4フェーズのチェックリストを作成" } ], deliverables: [ { title: "有料コンテンツ_資金調達補助金活用チェックリスト", type: "md", at: "now", path: "logs/kohomada_2026-07-28_有料コンテンツ_資金調達補助金活用チェックリスト_v1.md" } ] },
    { id: "T47", title: "note収益化：第1弾「海外バイヤー開拓メールテンプレ集」記事化（コホマダ貿易）", owner: "カエデ", status: "review", progress: 100, hint: "サトルの候補選定（社長承認済み）を受け、note記事としてそのまま公開できる形に仕上げ。タイトル・ハッシュタグ・画像プロンプト・本文（無料＝初回コンタクト／有料＝フォローアップ以降）を作成。想定価格300円。アオイ監査でPASS WITH CONDITIONS（区切り指示の紛らわしさを修正済み）", cmd: "T47を確認しました。この内容でnoteに公開します", log: [ { time: "now", text: "note記事下書きを作成（タイトル・ハッシュタグ7個・画像プロンプト・本文4テンプレ）" }, { time: "now", text: "アオイ監査：PASS WITH CONDITIONS。区切り指示文が本文と紛らわしかった点を修正し反映" } ], deliverables: [ { title: "有料note記事下書き_海外バイヤーメールテンプレ集", type: "md", at: "now", path: "logs/kohomada_2026-07-29_有料note記事下書き_海外バイヤーメールテンプレ集_v1.md" } ] },
    { id: "T48", title: "無料note「\"違憲判決\"で消えたはずの関税が...」記事：未監査分の監査・修正（コホマダ貿易・8/3公開予定）", owner: "アオイ", status: "review", progress: 100, hint: "REVISE→修正済み。①最高裁判決の引用先URLが誤っていた（4月のCAPE記事を引用していたが、実際は2月の別記事が正しい出典。判決自体は事実で6-3・Learning Resources Inc. v. Trump）②301条関税の階層を2段階→正しい3段階に修正、日本の分類を訂正③JETRO調査の対象社数「約3,300社」→正しくは9,647社に送付・有効回答3,369社に修正（56.1%/47.3%の数値自体は検証の結果正確だった）。Notion内の下書きを直接修正済み。経産省ページ[4]は403で今回検証不可のまま", cmd: "T48の監査・修正内容を確認しました。この内容で8/3公開します", log: [ { time: "now", text: "note運用計画書で持ち越されていた未監査記事を監査。出典URLを実際に開いて本文と照合" }, { time: "now", text: "3件の事実誤認・出典URL誤りを発見しREVISE。社長の承認を受け、Notion下書きを直接修正（引用元差し替え・301条3段階への訂正・JETRO対象社数の訂正）" } ], deliverables: [ { title: "Notion下書き（修正済み）", type: "notion", at: "now", path: "https://app.notion.com/p/3ab040888e97817fb342dc347b95c017" } ] },
    { id: "T49", title: "無料note「n8nの業務自動化、実は\"導入前診断\"が9割」記事：監査（コホマダAI・8/24公開予定）", owner: "アオイ", status: "done", progress: 100, hint: "PASS。IPA「DX動向2026」・中小機構調査・n8nのSAP出資評価額($2.5bn→$5.2bn)をすべて出典と照合し一致を確認。「8割近く/6割」の数値はIPA press release本文には無いが併記のIT Leaders記事の表現と一致しており出典の使い方として妥当", cmd: "T49を確認しました", log: [ { time: "now", text: "コンテンツ下書きDB全体の確認依頼を受け、残っていた未監査記事を監査。IPA・中小機構・n8n公式ブログ・tech.euの各出典を実際に開いて照合し、事実誤認なしと判定" } ], deliverables: [] },
    { id: "T50", title: "note.com下書き6件をコンテンツ下書きDBに登録・本文同期・監査（コホマダ）", owner: "ジン", status: "review", progress: 100, hint: "社長がnote.com編集画面に直接作成した下書き6件がNotion DB未登録だったため発覚。社長から本文提供を受け、画像プロンプト・ハッシュタグを既存記事と同形式で追加のうえ全件転記完了。アオイ監査：外部統計・法令の引用が無い解説/会社紹介コンテンツのため出典照合対象なし、断定表現・個人情報・機密混在なしでPASS。投稿予定日を設定（会社紹介系2件は7/31・8/1、貿易系2件は8/31・9/14、AI-DX系2件は9/7・9/21で既存の隔週サイクルに接続）", cmd: "T50を確認しました", log: [ { time: "now", text: "社長からnote.comとDBのズレを指摘され、6件のタイトルを特定" }, { time: "now", text: "マガジン分類が既存2区分に当てはまらない2件について、社長へ確認。「会社共通・その他」マガジンを新設し分類する提案が承認された" }, { time: "now", text: "スキーマにマガジン新区分を追加し、6件をプレースホルダーとして登録" }, { time: "now", text: "社長から全6件の本文提供を受領。画像プロンプト・ハッシュタグを追加して転記し、アオイが監査（PASS）。投稿予定日を設定し、既存の隔週サイクルに接続" } ], deliverables: [] },
    { id: "T51", title: "特定商取引法に基づく表示ページの下書き作成（コホマダ note有料コンテンツ用）", owner: "リョウ", status: "review", progress: 60, hint: "8/5の有料記事公開前に必須の準備。表示項目（販売業者・支払方法・返品条項等）の下書きを作成。代表者氏名・所在地・電話番号・メールアドレスは社長からの情報提供待ちのプレースホルダー。返品・キャンセル条項の有効性含め弁護士確認が必須。サイトへの実装は当社の対応範囲外（社長またはサイト管理者作業）", cmd: "", log: [ { time: "now", text: "有料記事・マガジンの運用方針を整理した際、8/5公開前に特商法表示ページが未設置と判明。社長の承認を受け下書きを作成" } ], deliverables: [ { title: "特定商取引法に基づく表示_下書き", type: "md", at: "now", path: "logs/kohomada_2026-07-29_特定商取引法に基づく表示_下書き_v1.md" } ] },
    { id: "T52", title: "設定精度レビュー：Hooks・クラウドルーティン7件の自動化設計確認（共通）", owner: "メイ", status: "review", progress: 100, hint: "レビュー完了。①Stopフック（日報リマインド）がmatcher指定なしで全セッション無差別適用のため無限ブロックの懸念、②log-dangerous-op.mjsがWebFetchを無条件で全件記録しログ肥大化の恐れ、③B4/B5/B6/B7と既存日次レポートが軒並み0時UTC(朝9時JST)台に集中しレビュー負荷が偏在、を指摘。承認設計（下書きのみ）自体は7件とも一貫と評価", cmd: "", log: [ { time: "now", text: "ジンより設定精度レビューの依頼を受け着手（logs/common_2026-07-29_設定精度レビュー依頼_v1.md参照）" }, { time: "now", text: "Hooks3件・settings.jsonを確認。Stopフックの適用範囲・log-dangerous-opの記録条件・cron時刻の集中を指摘して報告完了" } ], deliverables: [] },
    { id: "T53", title: "設定精度レビュー：KINOTO/FP事業コンテキストの事実精度確認（共通）", owner: "リサ", status: "review", progress: 100, hint: "レビュー完了・重要指摘あり。タスク一覧のT16「KINOTO HP作成」がtodo/progress0（＝HP未構築）にもかかわらず、HPブログ下書きルーティン(B6)がHP運営中を前提に設計されていた。またMEO(B5)もreference.mdの「現状の主要チャネルとして未確認」という留保が本文に反映されていなかった。ジン判断でB5・B6を一時停止済み。SKILL.mdのチラシ表記残存も指摘し修正済み。許認可・FP3級表記自体は全ルーティンで一貫と評価", cmd: "", log: [ { time: "now", text: "ジンより設定精度レビューの依頼を受け着手" }, { time: "now", text: "reference.md/SKILL.md・タスク一覧・7ルーティン全文を突合し、HP未構築/MEO未確認という重大な前提誤りを発見・報告" } ], deliverables: [] },
    { id: "T54", title: "設定精度レビュー：許認可・FP資格境界・外部公開ポリシー遵守確認（共通）", owner: "リョウ", status: "review", progress: 100, hint: "レビュー完了。下書き限定・断定表現回避・aoi監査依頼の設計は良好と評価。ただし①KINOTO系で許認可の有無自体への言及を禁止しきれていない、②FP/LinkedInで保険業法の募集人登録・金商法の投資助言/代理業登録という論点名が明記されていない、を指摘。許認可の具体名・番号は引き続き要弁護士/専門家確認", cmd: "", log: [ { time: "now", text: "ジンより設定精度レビューの依頼を受け着手" }, { time: "now", text: "rules4件・reference.md・ルーティン全文を確認し、許認可断定表現と資格境界の抜け穴を指摘して報告完了" } ], deliverables: [] },
    { id: "T55", title: "設定精度レビュー：最終独立監査（共通）", owner: "アオイ", status: "review", progress: 100, hint: "判定：PASS WITH CONDITIONS。メイ・リサ・リョウの指摘はすべて原文突合で妥当と確認。追加でNotion/Gmailログの本文断片残存リスクを検出（ジンが対応済み）。残タスクは①B4/B7の許認可・資格境界の追記（ジン対応済み）②KINOTO HP/MEOの実際の運用状況を鈴木さんに確認。承認不可事由（架空の法令・個人情報漏えい確定等）には該当せず", cmd: "", log: [ { time: "now", text: "メイ・リサ・リョウ・ジンの対応内容も含めて独立監査を実施。PASS WITH CONDITIONSと判定" } ], deliverables: [ { title: "設定精度レビュー依頼_v1", type: "md", at: "now", path: "logs/common_2026-07-29_設定精度レビュー依頼_v1.md" } ] },
    { id: "T56", title: "リスペクトマリン案件：WhatsApp下書き制約への対応方針レコメンド", owner: "メイ", status: "review", progress: 100, hint: "推奨：②手動運用案（n8nはWhatsApp文面のテキスト生成のみ、Send系ノードは一切使わず、送信は人間が手動で行う）。社長の承認待ち", cmd: "②の手動運用案で承認します／①除外案にします", log: [ { time: "now", text: "検討に着手" }, { time: "now", text: "3案を比較し②手動運用案を明確に推奨。実施手順まで提示" } ], deliverables: [ { title: "T56 WhatsApp対応方針レコメンド", type: "md", at: "now", path: "logs/kohomada_2026-07-28_T56WhatsApp対応方針レコメンド_v1.md" } ] },
    { id: "T57", title: "日本進出n8nワークフロー案：n8n公式提出基準の一次情報リサーチ（コホマダAI）", owner: "リサ", status: "todo", progress: 0, hint: "本セッションはWebSearch/WebFetchツールが利用できず未着手。n8n公式サイト（n8n.io/workflows）・community workflow submission guidelinesの一次情報確認、および『日本進出』文脈での自動化ニーズの裏付け調査を、Web検索可能な環境であらためて実施する必要あり。T61の統合案は暫定の仮説段階", cmd: "", log: [ { time: "now", text: "ジンより依頼を受領。ただし本セッションのツール構成にWebSearch/WebFetchが含まれず、一次情報確認は着手できないまま次回へ持ち越し" } ], deliverables: [] },
    { id: "T58", title: "日本進出n8nワークフロー案：外国企業の日本市場参入における業務課題整理（コホマダ）", owner: "レン", status: "review", progress: 100, hint: "kohomada-business-context（日本進出支援）を踏まえ、法人設立・許認可・現地調査・商談後フォロー・規制モニタリングの5領域で一般化した業務課題を整理。特定の実案件データは使用していない仮説ベースの整理。社長のご確認をお願いします", cmd: "T58を確認しました", log: [ { time: "now", text: "ジンより依頼を受け、コホマダの日本進出支援領域の業務課題を5領域に整理。統合レポートに反映" } ], deliverables: [ { title: "日本進出n8nワークフロー案（統合レポート）", type: "md", at: "now", path: "logs/kohomada_2026-08-15_日本進出n8nワークフロー案_v1.md" } ] },
    { id: "T59", title: "日本進出n8nワークフロー案：ワークフロー設計方針・自動化アイデア具体化（コホマダAI）", owner: "メイ", status: "review", progress: 100, hint: "T58の業務課題を踏まえ5案を概念設計（トリガー・ノード構成・連携サービスの概要）。ノードの正式名称・typeVersion・料金プランは未確認のため[要公式確認]。実装（JSON化）はまだ行っていない", cmd: "T59を確認しました", log: [ { time: "now", text: "T58を受け、5件のワークフロー概念設計を作成。費用対効果・承認ポイントの観点も付記" } ], deliverables: [ { title: "日本進出n8nワークフロー案（統合レポート）", type: "md", at: "now", path: "logs/kohomada_2026-08-15_日本進出n8nワークフロー案_v1.md" } ] },
    { id: "T60", title: "日本進出n8nワークフロー案：実装可能性の技術フィードバック（コホマダAI）", owner: "エイト", status: "review", progress: 60, hint: "メイの5案について実現可能性の一次見立てのみ実施（フル実装は次フェーズ）。本セッションはWebSearchが使えずn8n公式ノード仕様を確認できていないため、正式なtype/typeVersion確認とn8n-automation/配下のn8n-schema-researcherによる仕様検証が実装着手前に必須", cmd: "T60を確認しました", log: [ { time: "now", text: "5案とも一般的なn8n標準ノード（Schedule Trigger/Webhook/RSS Read/HTTP Request/AI Agent等）の組み合わせで概ね実現可能と見立てたが、正式仕様は未確認のまま" } ], deliverables: [ { title: "日本進出n8nワークフロー案（統合レポート）", type: "md", at: "now", path: "logs/kohomada_2026-08-15_日本進出n8nワークフロー案_v1.md" } ] },
    { id: "T61", title: "日本進出n8nワークフロー案：統合レポート作成（コホマダ・n8n公式提出前のアイデア出し）", owner: "ジン", status: "review", progress: 90, hint: "T58〜T60を統合し、審査に通過しやすいワークフロー案5件をまとめた。ただしn8n公式の提出・審査基準（T57）は本セッションでは一次確認できておらず、通過見込みの記述はすべて仮説段階。社長には『アイデア出しのたたき台』としてご確認いただき、次はリサの一次情報確認→アオイの監査→社長承認、の順で進める想定", cmd: "T61を確認しました。この5案で一次情報確認を進めて", log: [ { time: "now", text: "社長より『日本進出テーマのn8nワークフローをn8n公式に提出したい、まずアイデア出しから』と依頼。対象事業はコホマダ（日本進出支援×AI・業務自動化の交差領域）と特定" }, { time: "now", text: "本セッションのツール構成にTask（サブエージェント起動）・WebSearch/WebFetchが含まれないことを確認。実際の並列サブエージェント起動・Web一次情報確認は実施不可のため、ジンが直接、業務課題整理（レン相当）・ワークフロー概念設計（メイ相当）・実現可能性の一次見立て（エイト相当）を行い、その旨を明記した統合レポートを作成した" }, { time: "now", text: "n8n公式の提出・審査基準はリサによる一次情報確認（WebSearch/WebFetch可能な環境）が未実施のため、通過見込みはすべて[仮説]として明記。統合レポートlogs/kohomada_2026-08-15_日本進出n8nワークフロー案_v1.mdを作成" } ], deliverables: [ { title: "日本進出n8nワークフロー案（統合レポート）", type: "md", at: "now", path: "logs/kohomada_2026-08-15_日本進出n8nワークフロー案_v1.md" } ] },
  ],
  proposals: [],

  employees: [
    { name: "ジン", status: "review", taskId: "T61" },
    { name: "リサ", status: "todo", taskId: "T57" },
    { name: "レン", status: "review", taskId: "T58" },
    { name: "サトル", status: "review", taskId: "T41" },
    { name: "カエデ", status: "review", taskId: "T47" },
    { name: "メイ", status: "review", taskId: "T59" },
    { name: "エイト", status: "review", taskId: "T60" },
    { name: "ノヴァ", status: "idle", taskId: "" },
    { name: "ミナ", status: "review", taskId: "T37" },
    { name: "リョウ", status: "review", taskId: "T54" },
    { name: "アオイ", status: "idle", taskId: "" },
  ],

  // ルーティン業務：事業（コホマダ／KINOTO／FP）ごとの定型運用（note・Instagram・X等）と対象アカウント。
  // 詳細・アカウントURLが未確認のものは追加せず、確認できたものだけを登録する（捏造しない）。
  routines: [
    {
      business: "kohomada",
      platform: "note",
      detail: "「貿易・海外展開マガジン」「AI/DX導入マガジン」を隔週交代でクラウドルーティンが自動下書き作成。鈴木さんがレビューしてnoteに手動公開（自動公開はしない）。X自動投稿は連携予定（詳細は随時更新）。",
      frequency: "毎週月曜7時頃（自動下書き作成、公開は都度手動）",
      accountLabel: "note.com/kohomadha",
      url: "https://note.com/kohomadha",
    },
    {
      business: "kinoto",
      platform: "Instagram",
      accountLabel: "KINOTO",
      detail: "投稿は鈴木さんによる手動投稿（従来「自動投稿を運用中」と記載していたが事実と異なると判明・訂正、2026-07-29）。投稿ネタはクラウドルーティン「KINOTO集客・SNS発信下書き自動生成」が毎週Notionに下書きを作成、投稿自体は引き続き手動。",
      frequency: "下書き自動生成：毎週月曜9時頃／投稿：都度手動",
      url: null,
    },
    {
      business: "kinoto",
      platform: "Instagram",
      accountLabel: "お片付けゴリラ（不用品回収）",
      detail: "投稿は鈴木さんによる手動投稿（従来「自動投稿を運用中」と記載していたが事実と異なると判明・訂正、2026-07-29）。詳細は随時更新。",
      frequency: null,
      url: null,
    },
    {
      business: "kinoto",
      platform: "HP運営",
      detail: "HP自体が未構築（タスクT16「KINOTO HP作成」が着手前）と判明したため、ブログ下書き自動生成ルーティンは2026-07-29付で一時停止中（リサのレビューで指摘）。HP公開後に再開予定。",
      frequency: "一時停止中",
      url: null,
    },
    {
      business: "kinoto",
      platform: "公式LINE運営",
      detail: "ブログ更新・ショート動画更新を配信。配信文案はクラウドルーティン「KINOTO集客・SNS発信下書き自動生成」が毎週Notionに下書きを作成、配信自体は手動。",
      frequency: "下書き自動生成：毎週月曜9時頃／配信：都度手動",
      url: null,
    },
    {
      business: "kinoto",
      platform: "MEO投稿",
      detail: "Googleビジネスプロフィールが実際に運用中か未確認のため、下書き自動生成ルーティンは2026-07-29付で一時停止中（リサのレビューで指摘）。GBP運用状況を鈴木さんに確認後、再開判断。",
      frequency: "一時停止中",
      url: null,
    },
    {
      business: "common",
      platform: "LinkedIn",
      detail: "鈴木さん個人の対応領域（事業開発・FP・AI）を横断した発信。特定1事業のチャネルではない。投稿ネタはクラウドルーティン「鈴木さんLinkedIn投稿下書き自動生成（事業開発・FP・AI）」が3領域をローテーションして作成、投稿自体は手動。FP関連はFP技能士3級のため、金融商品推奨・投資助言に該当する内容は扱わない。",
      frequency: "下書き自動生成：毎週水曜9時頃／投稿：都度手動",
      url: null,
    },
  ],

  links: [
    { title: "設定精度レビュー報告書（2026-07-29）", url: "https://docs.google.com/document/d/1M-wI97nwd8Ujgyex8iSaIy3wMOU5ffPrzqBNbFoOGZc/edit", type: "Googleドキュメント", business: "common" },
    { title: "設定精度レビュー報告書（Notion版）", url: "https://app.notion.com/p/3ab040888e9781829084c71ded34e03f", type: "Notion", business: "common" },
    { title: "ルーティン業務 全体マップ（2026-07-29時点）", url: "https://docs.google.com/document/d/11MCNJITBleI5vACG3ngyQNWFXZ-H13k2uP4woU9ePsU/edit", type: "Googleドキュメント", business: "common" },
    { title: "ルーティン業務 全体マップ（Notion版）", url: "https://app.notion.com/p/3ab040888e978128aaa6fa27fa6072b2", type: "Notion", business: "common" },
    { title: "株式会社コホマダ 公式サイト", url: "https://kohomadha.com/", type: "リンク", business: "kohomada" },
    { title: "情報管理スプレッドシート（コンサル案件・リード管理）", url: "https://docs.google.com/spreadsheets/d/1gh8eV8S3pES2Qy3uIe-WPL8T0l0XJ1tnWr5JspdMlc4/edit", type: "Googleスプレッドシート", business: "kohomada" },
    { title: "KINOTO 事業計画書", url: "https://docs.google.com/spreadsheets/d/1ojTXSHz-g0Jnerc-JFzbKnKv3nfq13A2eJ9sEqtr-Bw/edit", type: "Googleスプレッドシート", business: "kinoto" },
    { title: "【KINOTO】ご相談ヒアリングシート", url: "https://docs.google.com/spreadsheets/d/1EfIG0MlUkN_VzobwWgNvpnArYsSVUPeebeilEicjA9k/edit", type: "Googleスプレッドシート", business: "kinoto" },
    { title: "Notion：MONEY DOCK（FP相談・集客プロジェクト）", url: "https://app.notion.com/p/59de3f9b3116499aa37ead864d336277", type: "Notion", business: "fp" },
    { title: "Notion：🚀 事業開発ハブ（タスク・ナレッジ・リード管理）", url: "https://pricey-legume-14e.notion.site/3a9040888e9781efab1ccbf858f14c0e", type: "Notion", business: "common" },
    { title: "Notion：既存「一覧」ハブ（貿易・AI・金融・KINOTO資料 等）", url: "https://app.notion.com/p/226040888e9780f6bc83e6a4d38184ac", type: "Notion", business: "common" },
  ],

  activity: [
    { time: "now", who: "ジン", text: "📋 T57〜T61起票：社長より『日本進出テーマのn8nワークフローをn8n公式に提出したい、まずアイデア出しから』を受付。対象はコホマダ（日本進出支援×AI・業務自動化）。本セッションはTask/WebSearchツールが使えないため、ジンが直接、業務課題整理・ワークフロー概念設計・実現可能性の一次見立てを行い、n8n公式の審査基準は未確認[仮説]と明記した統合レポートを作成しました" },
    { time: "now", who: "ジン", text: "⚠️ 重要な制約：本セッションにはサブエージェント起動（Task）・Web検索（WebSearch/WebFetch）ツールが提供されていませんでした。そのため『リサが公式サイトを調査』『メイ・エイトが並行検討』という形の実際の並列実行はできておらず、ジンが単独で一次統合を行っています。この点は社長にも正直にご報告します" },
    { time: "now", who: "メイ", text: "💡 T56完了：WhatsApp制約への対応は「②手動運用案」（n8nは文面生成のみ、送信は人間が手動）を明確に推奨します。社長のご判断をお願いします" },
    { time: "now", who: "ジン", text: "📋 リスペクトマリン案件：社長がT23・T24（文面）・T25・T26・T27・T28を確認・承認。T24は送信先メールアドレス・宛名が未確定のため送信保留。T27で指摘されたWhatsApp制約の対応方針をメイに検討依頼（T56）" },
    { time: "now", who: "アオイ", text: "🔍 T55監査完了：判定はPASS WITH CONDITIONS。メイ・リサ・リョウの指摘はすべて原文で確認、誇張なしと評価。追加でNotion/Gmailログに本文断片が平文残存するリスクを検出" },
    { time: "now", who: "ジン", text: "🔧 アオイの指摘を受けlog-dangerous-op.mjsを修正（Notion/Gmail呼び出しはpage_id/件名のみ記録、本文は残さない）。B4(KINOTO SNS)・B7(LinkedIn)にリョウ指摘の許認可・資格境界の文言を追記。7ルーティン全件の残存誤字も洗い出して修正" },
    { time: "now", who: "ジン", text: "⚠️ リサの指摘を受け、KINOTO MEO投稿下書き・HPブログ下書きの2ルーティンを一時停止しました（HPはT16未着手で実体無し、MEOは運用状況未確認のため）。社長に現況確認予定" },
    { time: "now", who: "リサ", text: "🔎 T53完了：KINOTO HP未構築（T16todo）・MEO運用未確認という重大な前提誤りをB5/B6ルーティンで発見。許認可・FP3級表記自体は全ルーティンで一貫と評価" },
    { time: "now", who: "リョウ", text: "⚖️ T54完了：下書き限定・断定回避・aoi監査依頼の設計は良好。KINOTO許認可の有無自体への言及禁止が不徹底、FP/LinkedInで保険業法・金商法の論点名明記が無い点を指摘" },
    { time: "now", who: "メイ", text: "🔧 T52完了：Stopフックの適用範囲・WebFetchログの無条件記録・cron時刻の0時UTC集中を指摘。承認設計（下書きのみ）自体は7件一貫と評価" },
    { time: "now", who: "ジン", text: "🔧 T52〜T55：社長より本日設定したHooks・クラウドルーティン7件・事業コンテキストの「精度を上げたい」と依頼。メイ（自動化設計）・リサ（事実精度）・リョウ（許認可/資格境界）に並行レビューを依頼、完了後アオイが最終監査" },
    { time: "now", who: "ジン", text: "📓 note収益化企画（2026-07-28〜07-29）の経緯・決定事項・次回への申し送りをlogs/日報.mdにまとめました" },
    { time: "now", who: "リョウ", text: "⚖️ T51：8/5の有料記事公開前に必要な特定商取引法表示ページの下書きを作成しました。代表者名・住所・電話番号は社長の情報提供待ち、返品条項含め弁護士確認が必須です" },
    { time: "now", who: "アオイ", text: "✅ T50監査：会社紹介・方針系6記事はいずれも外部統計・法令の引用が無く出典照合対象なし。断定表現・個人情報・事業間混在も見当たらずPASS" },
    { time: "now", who: "ジン", text: "📋 T50完了：社長から共有された6記事の本文を、画像プロンプト・ハッシュタグ付きでNotionに転記。投稿予定日を設定し、既存の隔週サイクル（貿易/AI-DX）に接続しました。会社紹介系2件は7/31・8/1に先行公開の想定です" },
    { time: "now", who: "ジン", text: "📋 T50：社長がnote.comに直接作成していた下書き6件がDB未登録と判明。マガジン新区分「会社共通・その他」を新設し、6件をプレースホルダー登録。本文の同期は社長からの共有待ち" },
    { time: "now", who: "アオイ", text: "✅ T49完了：長らく未監査だった「n8nの業務自動化」記事も監査しPASS。これでコンテンツ下書きDB内の全9件（無料8件・有料1件）の状態確認・監査がすべて完了しました" },
    { time: "now", who: "アオイ", text: "⚠️ T48：無料記事「\"違憲判決\"で消えたはずの関税が...」を監査したところ、最高裁判決の引用元URL誤り・301条関税の階層誤り・JETRO調査の対象社数誤りの3件を発見しREVISEと判定" },
    { time: "now", who: "ジン", text: "✅ T48修正完了：社長承認を受け、Notion下書きを直接修正しました。8/3の無料note公開はこれで問題ありません" },
    { time: "now", who: "アオイ", text: "🔎 T47監査：PASS WITH CONDITIONS。区切り指示文が本文と紛らわしく誤コピーのリスクがあったため修正済み。断定表現・個人情報・事業間混在は無し" },
    { time: "now", who: "カエデ", text: "🎨 T47完了：note収益化の第1弾記事下書きを仕上げました。タイトル・ハッシュタグ・画像プロンプト・本文（無料＝初回コンタクト／有料＝以降3テンプレ）。想定価格300円" },
    { time: "now", who: "ミナ", text: "💰 T37完了：定期購読マガジンは運営中の価格変更が不可（変更には新マガジン作成＋旧マガジン終了が必要）と確定したため、単発記事で反応を見てから定期購読価格を決める進め方を提案しました。これで制度面の疑問はすべて解消です" },
    { time: "now", who: "ミナ", text: "💰 T37更新：社長からの追加共有（価格帯100〜10,000円等・定期購読の発行条件）を反映し、noteプレミアム月会費500円を固定費として損益分岐試算に追加しました" },
    { time: "now", who: "リサ", text: "🔎 T34確定：価格帯・定期購読マガジンの発行条件（noteプレミアム加入＋事前審査＋月1回以上更新義務、更新が無いと廃刊）を社長共有の一次情報で確定しました" },
    { time: "now", who: "ミナ", text: "💰 T37完了：社長が共有してくれたnote公式ヘルプの手数料ページを基に確定試算しました。単発記事は手取り約77〜86%、定期購読は約68〜76%です。以前の「10%＋30円」という二次情報は不正確だったと判明し訂正しました" },
    { time: "now", who: "ジン", text: "🚀 社長承認（実案件情報なし）を受け、7件の有料コンテンツ素材（T40〜T46）を並行制作しました：国別輸出入規制フレームワーク（レン）・バイヤー開拓メール（サトル）・貿易書類ひな形（レン）・AI導入ROI試算シート（ミナ）・AI導入チェックリスト（メイ）・n8nテンプレ企画（エイト）・補助金チェックリスト（ミナ）" },
    { time: "now", who: "サトル", text: "📊 T39完了：T38の調査を踏まえ、貿易/AI・DX/金融の3領域ごとに有料コンテンツ候補（テンプレ・チェックリスト・DL素材）を具体化しました。無料＝信頼構築、有料＝実行支援で切り分けています" },
    { time: "now", who: "リサ", text: "🔎 T38完了：社長の「どんなコンテンツならお金に変わるか」を受けて、売れる有料記事の型と定期購読マガジンの制度詳細（要一次確認）を調査しました。貿易特化の売れ筋事例は見つかりませんでした" },
    { time: "now", who: "リョウ", text: "⚖️ T36完了：コホマダは法人運用のため特商法上の「業として」該当性が高いとの整理をしました。表示義務・リスク・弁護士へ確認すべき事項を整理済みです（条文原文の一次確認は次の一歩）" },
    { time: "now", who: "サトル", text: "📊 T35完了：社長の「両論併記」指示を受け、有料記事単発・定期購読マガジンの2モデルを比較しました。叩き台として、定期購読を軸に反響記事は単発切り出しする併用案を提案しています" },
    { time: "now", who: "ジン", text: "📋 note収益化（有料記事・サブスク）案件を受付。コホマダ公式note向けとして、T34（制度調査＝リサ・完了）→T35（導線・価格戦略＝サトル）・T36（特商法論点＝リョウ）・T37（価格試算＝ミナ）に振り分けました" },
    { time: "now", who: "リサ", text: "🔎 T34完了：note収益化の3形態と、note運営自身の特商法表記ページを確認しました。手数料率の正確な数値は公式ヘルプ本文への自動アクセスが403で拒否され未確認。社長ご自身のnote画面での確認をお願いしています" },
    { time: "now", who: "カエデ", text: "🎨 T31第3版：success-case-researchで確認した業界傾向（大きな文字・シンプルなレイアウト・配色3色以内・明確なCTA）を反映した4案（v3）を生成し、正式登録・「Claude作成デザイン」フォルダへ格納しました。v1・v2と合わせて計12案です" },
    { time: "now", who: "サトル", text: "📊 T31：リサの調査結果をSTPで自社に翻訳しました。特定企業の実績としてではなく業界の一般的傾向として、キャッチコピー拡大・高齢層向けの文字サイズ拡大・配色の絞り込みを提案しました" },
    { time: "now", who: "リサ", text: "🔎 T31：不用品回収・遺品整理・便利屋業のチラシ集客事例を調査。特定企業名での検証済み一次情報は見つからず、複数の業界メディア・ポスティング事業者記事（二次情報）から一般的傾向を確認しました" },
    { time: "now", who: "ジン", text: "🔧 T33修正：success-case-researchを「任意」ではなく、canva-creative-production等クリエイティブ系Skillの標準フローに標準ステップとして埋め込み直しました。以後、目的確認の直後に必ず他社事例調査が入ります" },
    { time: "now", who: "ジン", text: "🔍 T33完了：他社成功事例リサーチ→分析→クリエイティブ反映の標準フローを新設しました（success-case-research）。リサ→サトル→カエデの順で、架空の事例・数値を作らずに他社の学びを自社のクリエイティブに活かせます" },
    { time: "now", who: "カエデ", text: "🎨 T31改訂：STP・C.R.A.P.・AIDAを反映した改訂版4案（v2）をCanvaに登録し、「Claude作成デザイン」フォルダへ格納しました。旧v1と合わせて計8案からお選びいただけます" },
    { time: "now", who: "ジン", text: "🎓 T32完了：クリエイティブ制作の基礎スキル（リサーチ・マーケ・デザイン・コピー）を強化しました。リサ（3C/SWOT/PEST等）・サトル（STP/4P/ファネル等）・カエデ（C.R.A.P.原則・配色理論等）・コピー（AIDA/PAS/PREP等）、それぞれのSkill/エージェント定義に標準フレームワークを追加しました" },
    { time: "now", who: "カエデ", text: "🎨 T31：KINOTO総合チラシの生成案を4パターン、Canva上に作成しました！社長に選んでいただくのを待っています" },
    { time: "now", who: "サトル", text: "📊 T31：KINOTOチラシの訴求軸を整理しました。「暮らしの何でも相談窓口」ポジショニング・中高年〜高齢者とご家族がターゲット・落ち着いたトーン指定でカエデに引き継ぎました" },
    { time: "now", who: "ジン", text: "📋 KINOTOチラシ制作案件を受付。サトル→カエデの順で着手、T31として起票しました" },
    { time: "now", who: "ジン", text: "📑 T30完了：案件サマリーをGoogleドキュメント化し、3ワークフローの初心者向け設計図をArtifactページとして公開しました。社内共有の準備が整いました" },
    { time: "now", who: "ジン", text: "📄 T29完了：社内共有用の案件サマリーを作成し、n8nワークフロー3件を単体JSONファイル（n8n-workflows/）に整理しました。README付きでそのままインポート・共有できます" },
    { time: "now", who: "エイト", text: "✅ T28完了：①④⑤のデモ用n8nワークフローJSONを実装しました（Webhookダミートリガー・Gmail Credential未設定）。未検証のため、実インスタンスでのインポート検証が次の一歩です" },
    { time: "now", who: "ジン", text: "🛠️ 社長の指示でエイトがT28（デモ用n8nワークフローJSON、①④⑤メール版）の実装に着手しました。本番接続・Credentialは行いません" },
    { time: "now", who: "エイト", text: "⚠️ T27完了：n8nの通知・承認フロー設計は完成しましたが、WhatsApp公式ノードに「下書きのみ」の操作がなく、送信は人間が行うという方針と矛盾する制約を発見しました。要判断です" },
    { time: "now", who: "リサ", text: "🔎 T26完了：ANPDの越境移転規則の猶予期限（2025-08-23）が既に経過済みという見立てを、複数の法律事務所情報で裏付けました（決議原文そのものの確認はまだ）" },
    { time: "now", who: "ジン", text: "📌 案件整理を再確認。T25から浮かんだ未確認事項をT26（リサ）・T27（エイト）として新たに割り振り、着手しました" },
    { time: "now", who: "メイ", text: "🛠️ T25完了：Phase1自動化設計をまとめました。写真→報告書テンプレート自動流し込み＋PDF生成はカスタム開発、通知・承認フローはn8n（エイト委任）で切り分け。技術スタック確定はディスカバリーコール後です" },
    { time: "now", who: "ジン", text: "🛠️ 社長のご指名でメイがT25（自動化アーキテクチャ設計）に着手しました" },
    { time: "now", who: "アオイ", text: "🔎 T23監査完了：判定PASS WITH CONDITIONS。指摘6件（基準日宣言・ANPD期限リスク・T11/T24方針不一致・出典漏れ・二次情報明記・署名欄）をT11・T21・T22・T24に反映しました。ANPD移行期限の一次確認のみ残っています" },
    { time: "now", who: "ジン", text: "🔍 Q11の趣旨は社長確認待ちのため、支障のない範囲でT23（アオイによる独立監査）に着手しました" },
    { time: "now", who: "ジン", text: "📝 社長がT11・T21・T22を承認。フォローとしてT24（Q11・正式法人名の事前確認メール下書き）を作成しました。送信は社長のご判断・操作でお願いします" },
    { time: "now", who: "ジン", text: "✅ T11が完了・確認待ちに。下書き2件は完全重複と判明、先方の実回答（ブリーフ）を反映したコールアジェンダを作成しました。T11・T21・T22すべて確認待ちです" },
    { time: "now", who: "ジン", text: "✅ T21（リサ）・T22（リョウ）が完了し、確認待ち（review）になっています。次はT11（レン）への統合が焦点です" },
    { time: "now", who: "ジン", text: "🚀 T21（リサ）・T22（リョウ）を並行で着手しました。T11（レン）はこの2つの結果を踏まえて統合する順にします" },
    { time: "now", who: "ジン", text: "📌 リスペクトマリン案件を整理しました。T11（コール準備資料の統合＝レン）→T21（要確認事項の追加リサーチ＝リサ）・T22（契約・LGPD論点整理＝リョウ）→T23（最終監査＝アオイ）の順で進めます。技術構成（メイ）は正式スコープ確定後に着手予定です" },
    { time: "now", who: "アイ", text: "🔁 ルーティン業務にコホマダ（note）・KINOTO（Instagram×2・HP運営・公式LINE運営・MEO投稿）・FP（LinkedIn）の定型運用を登録しました。詳細は随時更新予定です" },
    { time: "now", who: "アイ", text: "📋 コホマダ貿易・AI・金融、KINOTOの案件・タスクを20件まとめて起票しました（T1〜T20）。担当社員に振り分け済みです" },
    { time: "now", who: "アイ", text: "🏢 事業体制を再編しました！AI美女アカウント運営事業を廃止し、株式会社コホマダ／株式会社DKN Enterprise（KINOTO）／個人FP事業の3事業体制に移行しました" },
    { time: "now", who: "アイ", text: "👥 チームを11名に再編しました：ジン（統括）・リサ（調査）・レン（事業開発）・サトル（マーケ）・カエデ（クリエイティブ）・メイ（自動化設計）・エイト（n8n実装）・ノヴァ（Web/3D）・ミナ（財務/FP/補助金）・リョウ（法務）・アオイ（品質監査）" },
    { time: "now", who: "アイ", text: "🧹 これまでのタスク・活動ログ・売上ボードを新体制に合わせてリセットしました。ここからが新しいスタートです" },
  ],

  command: { id: "reorg-20260725", type: "meeting" },
};
